---
- name: Add Docker APT repository GPG key
  ansible.builtin.apt_key:
    url: "{{ docker_gpg_url }}"
    state: present

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_repo_options }}"
    state: present

- name: Update APT package index
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes

- name: Install Docker packages
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present

- name: Ensure Docker service is enabled and started
  ansible.builtin.service:
    name: docker
    enabled: "{{ docker_service_enabled }}"
    state: "{{ docker_service_state }}"

- name: Add users to Docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"
  when: docker_users | length > 0

- name: Install Docker SDK for Python
  ansible.builtin.pip:
    name: docker
    version: "{{ docker_sdk_for_python_version }}"
  when: docker_sdk_for_python_install

- name: Install Docker Compose
  ansible.builtin.command:
    cmd: "curl -L https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose"
  when: docker_compose_install

- name: Ensure Docker Compose binary is executable
  ansible.builtin.file:
    path: /usr/local/bin/docker-compose
    mode: "0755"
  when: docker_compose_install

- name: Install Docker Compose bash completion
  ansible.builtin.command:
    cmd: "curl -L https://raw.githubusercontent.com/docker/compose/{{ docker_compose_version }}/contrib/completion/bash/docker-compose -o /etc/bash_completion.d/docker-compose"
  when: docker_compose_bash_completion_install
