- name: Set up code
  include_tasks: set-up-code.yml

- name: Build image
  include_tasks: build-image.yml
  
- name: Deploy web service container
  community.docker.docker_container:
    name: "{{ web_container_name }}"
    image: "{{ web_image }}:{{ web_image_tag }}"
    state: started
    ports:
      - "{{ web_port }}:80"
