- name: Check if the destination directory already exists
  ansible.builtin.stat:
    path: "{{ web_git_credentials }}"
  register: git_clone_dir

- name: Clone web application repository if it does not exist
  ansible.builtin.git:
    repo: "{{ web_git_credentials }}"
    dest: "{{ web_clone_dest }}"
    version: "{{ web_repo_version }}"
    force: yes
  when: not git_clone_dir.stat.exists

- name: Pull the latest changes 
  ansible.builtin.command:
    cmd: "git pull origin {{ web_repo_version }}"
    chdir: "{{ web_git_credentials }}"
  when: git_clone_dir.stat.exists
